{{- if .Values.operator.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: etcd-operator-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-operator-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: etcd-operator-{{ .Release.Name }}
    spec:
      serviceAccountName: etcd-operator-{{ .Release.Name }}-sa
      containers:
        - name: operator
          # TODO(neoaggelos): https://github.com/neoaggelos/etcd-operator/pull/1
          # Update to a stable build once PR is merged upstream
          image: neoaggelos/etcd-operator:0.10.0-5
          command:
            - /operator
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{ end }}
